version: "3.8"

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium_grid
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"

  gradle:
    image: gradle:8.6.0-jdk17
    container_name: gradle_tests
    depends_on:
      - selenium
    volumes:
      - .:/home/gradle/project
    working_dir: /home/gradle/project
    command: tail -f /dev/null